# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys

oem: "Infinix"             # The company that made your device (e.g. Samsung)
device: "Infinix-X6962"          # The device code. May be same as model code.
android_version: "14" # Only put in the major version number.
build_tag: "UP1A.231005.007"       # Example: RKQ1.211119.001
model: "Infinix ZERO Flip"           # The model code. (e.g. SM-T380)

variants:
  - variant: "Global"
    product: "X6962-OP"         # The product code. May be same as device code or model code.
    incremental: "251107V2494"     # Example: 2206131341

  - variant: "India"
    product: "X6962-IN"
    incremental: "251107V2494"

  - variant: "Russia"
    product: "X6962-RU"
    incremental: "251107V2494"
