# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys

oem: "itel"             # The company that made your device (e.g. Samsung)
product: "S688LN-OP"         # The product code. May be same as device code or model code.
device: "itel-S688LN"          # The device code. May be same as model code.
android_version: "15" # Only put in the major version number.
build_tag: "AP3A.240905.015.A2"       # Example: RKQ1.211119.001
incremental: "131060"     # Example: 2206131341
model: "itel Super 26 Ultra"           # The model code. (e.g. SM-T380)
