# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys

oem: "Infinix"             # The company that made your device (e.g. Samsung)
product: "X1301-OP"         # The product code. May be same as device code or model code.
device: "Infinix-X1301"          # The device code. May be same as model code.
android_version: "14" # Only put in the major version number.
build_tag: "UKQ1.240826.001"       # Example: RKQ1.211119.001
incremental: "251218V74"     # Example: 2206131341
model: "Infinix XPAD GT (SD888)"           # The model code. (e.g. SM-T380)
