# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys

oem: "Infinix"             # The company that made your device (e.g. Samsung)
device: "Infinix-X6857"          # The device code. May be same as model code.
android_version: "15" # Only put in the major version number.
build_tag: "AP3A.240905.015.A2"       # Example: RKQ1.211119.001
model: "Infinix NOTE 50X 5G"           # The model code. (e.g. SM-T380)

variants:
  - variant: "Global"
    product: "X6857-OP"         # The product code. May be same as device code or model code.
    incremental: "153014"     # Example: 2206131341

  - variant: "India"
    product: "X6857B-IN"
    device: "Infinix-X6857B"
    incremental: "153003"
